---
title: "Plot_ML-Analysis_Results"
author: "Charlotte Meinke, Rebecca Delfendahl"
date: "2024-11-15"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    df_print: paged
params:
  response_criterion: "Response_BAT" # choose between "Response_FSQ_50", and "Response_BAT" 
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Packages
```{r}
windowsFonts(Arial=windowsFont("Arial"))
library(readr)
library(dplyr)
library(flextable)
library(ggplot2)

# User-defined functions
source("../Useful_functions.R")
```

# Settings
```{r}
basic_path = "Y:\\Psythera\\Projekte_Meinke\\Old_projects\\Labrotation_Rebecca\\2_Machine_learning"
path_results_folder = file.path(basic_path, "Results\\RT-trimmed-RT-wrong-removed_outliers-removed", params$response_criterion)
plots_path = file.path(path_results_folder, "Plots/")
dir.create(plots_path)

family = "Arial"
theme_set(theme_bw() + theme(text = element_text(family = family),
                                  axis.title = element_text(size = 24),
                                  axis.title.y = element_text(size = 24, margin = margin(r = 30)), 
                                  axis.text = element_text(size = 18),
                                  #legend.text = element_text(size = 18),
                                  strip.text = element_text(size = 20)
                                  #plot.title = element_text(size = size_text, family = family)
                                  #panel.spacing.x = unit(3, "lines")
                                  ))
# or theme_classic()
```

# Functions
```{r}
# Get all folders in the results folder (each containing the results of another model)
load_and_combine_results <- function(path_results_folder, file_name){
  results_folders <- list.files(path = path_results_folder, full.names = FALSE)

  # Filter for new results
  results_folders <- results_folders[grepl("final", results_folders)& !grepl("permuted", results_folders)]

  # For each folder, save the file of interest in dictionary
  results_dict = list()
  for (folder_name in results_folders) {
  # Read the file and store it as a dictionary
  results_dict[[folder_name]] <- read.delim(file.path(path_results_folder, folder_name,
                                                      paste0(file_name,".txt")))
  }
  # Combine results
  combined_results <- bind_rows(results_dict, .id = "FolderName")
  combined_results$X <- NULL
  
  return(combined_results)
}
```

## Functions for classification
```{r}
rename_classifier_models <- function(classification_results){
  # Create new model variable with nice modelnames
classification_results$Model <- ifelse(grepl("random_forest_clf_yes_smote_oversampling", classification_results$FolderName),
                                       "Random Forest\n(OS: SMOTE)",
                    ifelse(grepl("random_forest_clf_yes_simple", classification_results$FolderName),
                           "Random Forest\n(OS: Simple)",
                    ifelse(grepl("random_forest_clf_no_oversampling", classification_results$FolderName),
                           "Random Forest\n(OS: no)",
                    ifelse(grepl("svm_clf_yes_smote", classification_results$FolderName),
                           "Rbf-SVM\n(OS: SMOTE)",
                    ifelse(grepl("svm_clf_yes_simple", classification_results$FolderName), 
                           "Rbf-SVM\n(OS: Simple)",
                    ifelse(grepl("svm_clf_no_oversampling", classification_results$FolderName), 
                           "Rbf-SVM\n(OS: no)", NA))))))
# Ensure correct ordering
classification_results$Model <- factor(classification_results$Model, levels = c("Random Forest\n(OS: SMOTE)","Random Forest\n(OS: Simple)",
                                                                                "Random Forest\n(OS: no)","Rbf-SVM\n(OS: SMOTE)", "Rbf-SVM\n(OS: Simple)","Rbf-SVM\n(OS: no)"))

classification_results$FeatureSet <- ifelse(grepl("clinical_features", classification_results$FolderName),
                                  "clinical", "executive_functioning")

return(classification_results)
}

create_classification_plot <- function(results_df){
  # Ensure correct ordering
  results_df$Model <- factor(results_df$Model, levels = c("Random Forest\n(OS: SMOTE)","Random Forest\n(OS: Simple)","Random Forest\n(OS: no)","Rbf-SVM\n(OS: SMOTE)",
                                                             "Rbf-SVM\n(OS: Simple)","Rbf-SVM\n(OS: no)"))
  
  # Define feature sets and specify colors
  results_df$FeatureSet <- dplyr::recode(results_df$FeatureSet, clinical = "Clinical Features", executive_functioning = "Clinical + Executive\nFunctioning Features")
  colors <- c("Clinical Features" = "white", "Clinical + Executive\nFunctioning Features" = "#D3D3D3")
  
  # Set factor levels for FeatureSet to control order in the plot
  results_df$FeatureSet <- factor(results_df$FeatureSet, levels = c("Clinical Features", "Clinical + Executive\nFunctioning Features"))
  
  # Create ggplot
  plot <- ggplot(results_df, aes(x=FeatureSet, y=balanced_accuracy, fill=FeatureSet)) +
    geom_violin(scale = "width") +
    geom_jitter(size = 1, width = 0.2, height = 0) + 
    stat_summary(
      geom = "point",
      shape = 24,
      fun = "mean",
      col = "black",
      fill = "red",
      size = 3
    ) +
    labs(y = "Balanced Accuracy",  x = "", fill = "Feature Set") + 
   
    scale_y_continuous(breaks = c(0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)) +
    scale_fill_manual(values = colors) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none") +
    geom_rect(data = subset(results_df, Model == "Random Forest\n(OS: SMOTE)"), 
                          fill = NA, colour = "black", size = 1.5, xmin = -Inf,xmax = Inf,
            ymin = -Inf,ymax = Inf) +
    facet_wrap(~Model, nrow = 1) 
 

  return(plot)
}
```


# Load and combine results
```{r}
# Get all folders in the results folder (each containing the results of another model)
classification_results <- load_and_combine_results(path_results_folder, file_name = "performance_across_iters")
```

# Create a plot for the classification results
```{r, fig.width = 16, fig.height = 9}
classification_results <- rename_classifier_models(classification_results)
classification_plot <- create_classification_plot(results_df = classification_results)
classification_plot
```

## Save plots
```{r}
ggsave(file.path(plots_path,"Classification_results_plot.png"), plot = classification_plot, width = 16, height = 9, dpi = 300)
```

# Summarize classificiaton results in a table
## Load and combine summary_metrics
```{r}
# Get all folders in the results folder (each containing the results of another model)
combined_results <- load_and_combine_results(path_results_folder, file_name = "performance_summary")

# Separate into regressor and classifier dataframes
classification_results <- combined_results[grepl("clf", combined_results$FolderName), ]

# Rename models
classification_results <- rename_classifier_models(classification_results)
```

## Collect summary metrics in a table
```{r}
metrics <- c("accuracy", "balanced_accuracy", "sensitivity", "specificity", "f1_score", "auc")

# Compute mean (SD) for each metric per model
formatted <- sapply(metrics, function(m) {
  mean_col <- classification_results[[paste0("Mean_", m)]]
  std_col  <- classification_results[[paste0("Std_", m)]]
  sprintf("%.2f (%.2f)", mean_col, std_col)
})

# Summary table all models
summary_table <- data.frame(Model = classification_results$Model, FeatureSet = classification_results$FeatureSet, formatted, check.names = FALSE)
colnames(summary_table) <- c("Model", "FeatureSet", "Accuracy", "Balanced Accuracy", "Sensitivity", "Specificity", "F1-Score", "AUC-Score")

summary_table_clin <- summary_table[summary_table$FeatureSet == "clinical",]
summary_table_clin$FeatureSet <- NULL

summary_table_exec <- summary_table[summary_table$FeatureSet == "executive_functioning",]
summary_table_exec$FeatureSet <- NULL
```

## Save as flextable
```{r}
create_save_flextable(table_pub = summary_table_clin, results_path = plots_path, file_name = "classification_results_clinical.docx")

create_save_flextable(table_pub = summary_table_exec, results_path = plots_path, file_name = "classification_results_executive.docx")
```
