---
title: "Plot_ML-Analysis_Results"
author: "Charlotte Meinke, Rebecca Delfendahl"
date: "2024-11-15"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    df_print: paged
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Packages
```{r}
windowsFonts(Arial=windowsFont("Arial"))
library(readr)
library(dplyr)
library(flextable)
library(ggplot2)

# User-defined functions
source("../Useful_functions.R")
```

# Plot Settings
```{r}
family = "Arial"
theme_set(theme_bw() + theme(text = element_text(family = family),
                                  axis.title = element_text(size = 24),
                                  axis.title.y = element_text(size = 24, margin = margin(r = 30)), 
                                  axis.text = element_text(size = 18),
                                  #legend.text = element_text(size = 18),
                                  strip.text = element_text(size = 20)
                                  #plot.title = element_text(size = size_text, family = family)
                                  #panel.spacing.x = unit(3, "lines")
                                  ))
# or theme_classic()
```

# Load and combine results
```{r}
# Get all folders in the results folder (each containing the results of another model)
basic_path = "Y:\\Psythera\\Projekte_Meinke\\Old_projects\\Labrotation_Rebecca\\2_Machine_learning"
path_results_folder = file.path(basic_path, "Results\\RT_trimmed_RT_wrong_removed_outliers-removed\\response_FSQ")
results_folders <- list.files(path = path_results_folder, full.names = FALSE)

# Filter for new results
results_folders <- results_folders[grepl("final", results_folders)& !grepl("permuted", results_folders)]

# For each folder, save the performance_across_iters-file in dictionary
results_dict = list()
for (folder_name in results_folders) {
  # Read the file and store it as a dictionary
  results_dict[[folder_name]] <- read.delim(file.path(path_results_folder, folder_name,
                                                      "performance_across_iters.txt"))
}

# Combine results
combined_results <- bind_rows(results_dict, .id = "FolderName")
combined_results$X <- NULL

# Separate into regressor and classifier dataframes
classification_results <- combined_results[grepl("clf", combined_results$FolderName), ]
regression_results <- combined_results[grepl("regressor", combined_results$FolderName), ]
```

# Prepare classification results
```{r}
# Create new model variable
classification_results$Model <- ifelse(grepl("random_forest_clf_yes_smote_oversampling", classification_results$FolderName),
                                       "Random Forest\n(OS: SMOTE)",
                    ifelse(grepl("random_forest_clf_yes_simple", classification_results$FolderName),
                           "Random Forest\n(OS: Simple)",
                    ifelse(grepl("random_forest_clf_no_oversampling", classification_results$FolderName),
                           "Random Forest\n(OS: no)",
                    ifelse(grepl("svm_clf_yes_smote", classification_results$FolderName),
                           "Rbf-SVM\n(OS: SMOTE)",
                    ifelse(grepl("svm_clf_yes_simple", classification_results$FolderName), 
                           "Rbf-SVM\n(OS: Simple)",
                    ifelse(grepl("svm_clf_no_oversampling", classification_results$FolderName), 
                           "Rbf-SVM\n(OS: no)", NA))))))
# Ensure correct ordering
classification_results$Model <- factor(classification_results$Model, levels = c("Random Forest\n(OS: SMOTE)","Random Forest\n(OS: Simple)",
                                                                                "Random Forest\n(OS: no)","Rbf-SVM\n(OS: SMOTE)", "Rbf-SVM\n(OS: Simple)","Rbf-SVM\n(OS: no)"))
```

# Summarize in a table
```{r}
metrics <- c("accuracy", "balanced_accuracy", "sensitivity", "specificity", "f1_score", "auc")

# Compute mean (SD) for each metric per model
summary_table <- classification_results %>%
  group_by(Model) %>%
  summarise(across(all_of(metrics),
                   ~ paste0(round(mean(.x, na.rm = TRUE), 2),
                            " (", round(sd(.x, na.rm = TRUE), 2), ")"),
                   .names = "{.col}")) %>%
  ungroup()

colnames(summary_table) <- c("Model", "Accuracy", "Balanced Accuracy", "Sensitivity", "Specificity", "F1-Score", "AUC-Score")
```

# Save as flextable
```{r}
create_save_flextable(table_pub = summary_table, results_path = basic_path, file_name = "classification_results_FSQ.docx")
```


# Create a plot for the classification results
```{r, fig.width = 16, fig.height = 9}
create_classification_plot <- function(results_df){
  # Create new model variable
  results_df$Model <- ifelse(grepl("random_forest_classifier_yes_smote_oversampling", results_df$FolderName),
                             "Random Forest\n(OS: SMOTE)",
                      ifelse(grepl("random_forest_classifier_yes_simple", results_df$FolderName),
                             "Random Forest\n(OS: Simple)",
                      ifelse(grepl("random_forest_classifier_no_oversampling", results_df$FolderName),
                             "Random Forest\n(OS: no)",
                      ifelse(grepl("svm_classifier_yes_smote", results_df$FolderName),
                             "Rbf-SVM\n(OS: SMOTE)",
                      ifelse(grepl("svm_classifier_yes_simple", results_df$FolderName), 
                             "Rbf-SVM\n(OS: Simple)",
                      ifelse(grepl("svm_classifier_no_oversampling", results_df$FolderName), 
                             "Rbf-SVM\n(OS: no)", NA))))))
  # Ensure correct ordering
  results_df$Model <- factor(results_df$Model, levels = c("Random Forest\n(OS: SMOTE)","Random Forest\n(OS: Simple)","Random Forest\n(OS: no)","Rbf-SVM\n(OS: SMOTE)",
                                                             "Rbf-SVM\n(OS: Simple)","Rbf-SVM\n(OS: no)"))
  
  # Define feature sets and specify colors
  results_df$FeatureSet <- ifelse(grepl("clinical_features", results_df$FolderName),
                                  "Clinical Features", "Clinical + Executive\nFunctioning Features")
  colors <- c("Clinical Features" = "white", "Clinical + Executive\nFunctioning Features" = "#D3D3D3")
  
  # Set factor levels for FeatureSet to control order in the plot
  results_df$FeatureSet <- factor(results_df$FeatureSet, levels = c("Clinical Features", "Clinical + Executive\nFunctioning Features"))
  
  # Create ggplot
  plot <- ggplot(results_df, aes(x=FeatureSet, y=balanced_accuracy, fill=FeatureSet)) +
    geom_violin(scale = "width") +
    geom_jitter(size = 1, width = 0.2, height = 0) + 
    stat_summary(
      geom = "point",
      shape = 24,
      fun = "mean",
      col = "black",
      fill = "red",
      size = 3
    ) +
    labs(y = "Balanced Accuracy",  x = "", fill = "Feature Set") + 
   
    scale_y_continuous(breaks = c(0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)) +
    scale_fill_manual(values = colors) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none") +
    geom_rect(data = subset(results_df, Model == "Random Forest\n(OS: SMOTE)"), 
                          fill = NA, colour = "black", size = 1.5, xmin = -Inf,xmax = Inf,
            ymin = -Inf,ymax = Inf) +
    facet_wrap(~Model, nrow = 1) 
 

  return(plot)
}

classification_plot <- create_classification_plot(results_df = classification_results)
classification_plot 
```

# Create a plot for the regression results
```{r,fig.width = 16, fig.height = 9}
create_regression_plot <- function(results_df){
  # Create new model variable
  results_df$Model <- ifelse(grepl("random_forest_regressor", results_df$FolderName), "Random Forest",
                      ifelse(grepl("ridge_regressor", results_df$FolderName), "Ridge", NA))
  
  # Define feature sets and specify colors
  results_df$FeatureSet <- ifelse(grepl("clinical_features", results_df$FolderName),
                                  "Clinical Features", "Clinical + Executive\nFunctioning Features")
  colors <- c("Clinical Features" = "white", "Clinical + Executive\nFunctioning Features" = "#D3D3D3")
  
  # Set factor levels for FeatureSet to control order in the plot
  results_df$FeatureSet <- factor(results_df$FeatureSet, levels = c("Clinical Features", "Clinical + Executive\nFunctioning Features"))
  
  # Create ggplot
  plot <- ggplot(results_df, aes(x=FeatureSet, y=MSE, fill=FeatureSet)) +
    geom_violin(scale = "width") +
    geom_jitter(size = 1, width = 0.2, height = 0) + 
    stat_summary(
      geom = "point",
      shape = 24,
      fun = "mean",
      col = "black",
      fill = "red",
      size = 3
    ) +
    labs(y = "Mean Squared Error",  x = "", fill = "Feature Set") + 
    scale_fill_manual(values = colors) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "none") +
    facet_wrap(~Model, nrow = 1)

  return(plot)
}

regression_plot <- create_regression_plot(results_df = regression_results)
regression_plot
```

# Save plots
```{r}
plots_path = file.path(basic_path, "Plots/")
ggsave(file.path(plots_path,"Classification_results_plot.png"), plot = classification_plot, width = 16, height = 9, dpi = 300)
ggsave(file.path(plots_path, "Regression_results_plot.png"), plot = regression_plot, width = 16, height = 9, dpi = 300)
ggsave(file.path(plots_path,"Classification_results_plot.svg"), plot = classification_plot, width = 16, height = 9)
ggsave(file.path(plots_path, "Regression_results_plot.svg"), plot = regression_plot, width = 16, height = 9)
```
